import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import { Children } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <div className="bg-gray-100 text-gray-900 max-w-[300px] min-h-screen overflow-y-auto md:min-w-[220px]">
            <Sidebar />
          </div>
          <div className="bg-gray-100 text-black flex-1 h-screen overflow-hidden relative">
            <Header />
            {children}  /* Main content area */
          </div>
        </div>
      </body>
    </html>
  );
}
